version: '3'
services:
  postgresql:
    image: postgres
    container_name: kindergarten
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=kindergarten
      - POSTGRES_PASSWORD=kindergarten
      - POSTGRES_DATABASE=kindergarten
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-kindergarten
    ports:
      - "6379-6379"
